// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "UpboundAppMetadata/models"
)

// PostAppOKCode is the HTTP code returned for type PostAppOK
const PostAppOKCode int = 200

/*PostAppOK OK

swagger:response postAppOK
*/
type PostAppOK struct {
}

// NewPostAppOK creates PostAppOK with default headers values
func NewPostAppOK() *PostAppOK {

	return &PostAppOK{}
}

// WriteResponse to the client
func (o *PostAppOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAppBadRequestCode is the HTTP code returned for type PostAppBadRequest
const PostAppBadRequestCode int = 400

/*PostAppBadRequest Bad Request

swagger:response postAppBadRequest
*/
type PostAppBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequest `json:"body,omitempty"`
}

// NewPostAppBadRequest creates PostAppBadRequest with default headers values
func NewPostAppBadRequest() *PostAppBadRequest {

	return &PostAppBadRequest{}
}

// WithPayload adds the payload to the post app bad request response
func (o *PostAppBadRequest) WithPayload(payload *models.BadRequest) *PostAppBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post app bad request response
func (o *PostAppBadRequest) SetPayload(payload *models.BadRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAppBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
