// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostAppHandlerFunc turns a function with the right signature into a post app handler
type PostAppHandlerFunc func(PostAppParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAppHandlerFunc) Handle(params PostAppParams) middleware.Responder {
	return fn(params)
}

// PostAppHandler interface for that can handle valid post app params
type PostAppHandler interface {
	Handle(PostAppParams) middleware.Responder
}

// NewPostApp creates a new http.Handler for the post app operation
func NewPostApp(ctx *middleware.Context, handler PostAppHandler) *PostApp {
	return &PostApp{Context: ctx, Handler: handler}
}

/*PostApp swagger:route POST /app postApp

PostApp post app API

*/
type PostApp struct {
	Context *middleware.Context
	Handler PostAppHandler
}

func (o *PostApp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostAppParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
