// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "UpboundAppMetadata/models"
)

// PostAppOKCode is the HTTP code returned for type PostAppOK
const PostAppOKCode int = 200

/*PostAppOK OK

swagger:response postAppOK
*/
type PostAppOK struct {
}

// NewPostAppOK creates PostAppOK with default headers values
func NewPostAppOK() *PostAppOK {

	return &PostAppOK{}
}

// WriteResponse to the client
func (o *PostAppOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAppNotFoundCode is the HTTP code returned for type PostAppNotFound
const PostAppNotFoundCode int = 404

/*PostAppNotFound Not Found

swagger:response postAppNotFound
*/
type PostAppNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.NotFound `json:"body,omitempty"`
}

// NewPostAppNotFound creates PostAppNotFound with default headers values
func NewPostAppNotFound() *PostAppNotFound {

	return &PostAppNotFound{}
}

// WithPayload adds the payload to the post app not found response
func (o *PostAppNotFound) WithPayload(payload *models.NotFound) *PostAppNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post app not found response
func (o *PostAppNotFound) SetPayload(payload *models.NotFound) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAppNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
