// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Upbound App Metadata microservice",
    "title": "UpboundAppMetadata",
    "version": "0.1.0"
  },
  "paths": {
    "/app": {
      "get": {
        "operationId": "GetApp",
        "parameters": [
          {
            "type": "string",
            "description": "Title of the app",
            "name": "title",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AppObject"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      },
      "post": {
        "operationId": "PostApp",
        "parameters": [
          {
            "name": "AppMetadata",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AppObject"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AppObject": {
      "description": "The App Object",
      "type": "object",
      "required": [
        "title",
        "version",
        "maintainers",
        "company",
        "website",
        "source",
        "license",
        "description"
      ],
      "properties": {
        "company": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "license": {
          "type": "string"
        },
        "maintainers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Maintainer"
          }
        },
        "source": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "website": {
          "type": "string"
        }
      }
    },
    "BadRequest": {
      "description": "Bad Request object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Maintainer": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "NotFound": {
      "description": "Not Found object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Upbound App Metadata microservice",
    "title": "UpboundAppMetadata",
    "version": "0.1.0"
  },
  "paths": {
    "/app": {
      "get": {
        "operationId": "GetApp",
        "parameters": [
          {
            "type": "string",
            "description": "Title of the app",
            "name": "title",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AppObject"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/NotFound"
            }
          }
        }
      },
      "post": {
        "operationId": "PostApp",
        "parameters": [
          {
            "name": "AppMetadata",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AppObject"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AppObject": {
      "description": "The App Object",
      "type": "object",
      "required": [
        "title",
        "version",
        "maintainers",
        "company",
        "website",
        "source",
        "license",
        "description"
      ],
      "properties": {
        "company": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "license": {
          "type": "string"
        },
        "maintainers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Maintainer"
          }
        },
        "source": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "website": {
          "type": "string"
        }
      }
    },
    "BadRequest": {
      "description": "Bad Request object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Maintainer": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "NotFound": {
      "description": "Not Found object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
